on: push

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install deps
        run: npm i

      - name: run tests
        run: npm run test
